modLoader="javafml"
loaderVersion="[36,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Unown-Font/issues"
license="ARR"

[[mods]]
modId="unownfont"
updateJSONURL="https://updates.blamejared.com/get?n=unownfont&gv=1.16.5"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''